# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20161009_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado Em'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_courseprogress_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado Em'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_courseprogress_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, through='user.CourseProgress', to='course.Course', verbose_name='Cursos'),
        ),
    ]
