# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20161120_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
