# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20170115_1833'),
        ('user', '0004_courseprogress_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado Em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado Em')),
                ('sample', models.IntegerField(default=10, verbose_name='Quantidade de Questões')),
                ('answer', models.IntegerField(default=0, verbose_name='Respostas')),
                ('score', models.IntegerField(default=0, verbose_name='Desempenho')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quizprogress_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quizprogress_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='Estudante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='quizzes',
            field=models.ManyToManyField(blank=True, through='user.QuizProgress', to='quiz.Quiz', verbose_name='Simulados'),
        ),
    ]
