# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170509_1914'),
        ('user', '0005_auto_20170115_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizprogress',
            name='answer',
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='answers',
            field=models.ManyToManyField(blank=True, to='quiz.Answer', verbose_name='Respostas'),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Quantidade Respondida'),
        ),
    ]
