# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170604_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
