# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20160320_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lição', 'verbose_name_plural': 'Lições'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lesson', verbose_name='Lição'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='logo',
            field=models.ImageField(null=True, upload_to='course/activities/%Y/%m/%d', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='http://www.vimeo.com/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(null=True, upload_to='course/courses/%Y/%m/%d', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(max_length=500, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='logo',
            field=models.ImageField(null=True, upload_to='course/lessons/%Y/%m/%d', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Unit', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='logo',
            field=models.ImageField(null=True, upload_to='course/units/%Y/%m/%d', verbose_name='Logo'),
        ),
    ]
