# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20160814_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='course/activities/%Y/%m/%d', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='course/lessons/%Y/%m/%d', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='course/units/%Y/%m/%d', verbose_name='Logo'),
        ),
    ]
