# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20160814_1815'),
        ('quiz', '0002_auto_20170115_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Unit', verbose_name='Unidade'),
        ),
    ]
