# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='quiz.Question', verbose_name='Questões'),
        ),
    ]
